language: php

matrix:
  include:
    - php: '5.4'
      env: MU_LOADER_INSTALL_LOWEST=0
    - php: '5.6'
      env: MU_LOADER_INSTALL_LOWEST=0
    - php: '7.0'
      env: MU_LOADER_INSTALL_LOWEST=0
    - php: '5.4'
      env: MU_LOADER_INSTALL_LOWEST=1
    - php: '5.6'
      env: MU_LOADER_INSTALL_LOWEST=1
    - php: '7.0'
      env: MU_LOADER_INSTALL_LOWEST=1

before_script:
  - if [ 1 -eq $MU_LOADER_INSTALL_LOWEST ]; then composer update --prefer-lowest; else composer update; fi

script: composer test

after_script:
  - composer export-coverage && curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports

cache:
  directories:
    - vendor

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change
